version: '3.8'

services:

  postgres:
    image: postgres
    container_name: meu-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres.sql:/docker-entrypoint-initdb.d/postgres.sql

  adminer:
    image: adminer
    restart: always
    container_name: meu-adminer
    ports:
      - 8080:8080

  fiap-burger-java:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fiap-burger-java
    ports:
      - "8989:8989"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_DATASOURCE_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect

volumes:
  postgres-data:

