apiVersion: v1
kind: ConfigMap
metadata:
  name: constantes-configmap
  labels:
    name: constantes-configmap
data:
  spring.datasource.url: "jdbc:postgresql://db-fiap-burger-svc:5432/postgres"
  spring.datasource.driverClassName: "org.postgresql.Driver"
  spring.datasource.plataform: "org.hibernate.dialect.PostgreSQLDialect"
  spring.datasource.jpa.database-platform: "org.hibernate.dialect.PostgreSQLDialect"