apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tech-challenge-java-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fiap-burger-deployment
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70